GOENV: DEV
SERVICE_ID_GENERATEALGORITHM: SNOWFLAKE
SERVICE_ID_SNOWFLAKECONFIG_EPOCH: "1288351723598"
SERVICE_ID_SNOWFLAKECONFIG_NODEBITS: "10"
SERVICE_ID_SNOWFLAKECONFIG_NODEID: "1"
SERVICE_ID_SNOWFLAKECONFIG_STEPBITS: "12"
